apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    # ignore this error
    manifests:
      - ./infra/k8s/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: fahimmon/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*ts"
